Building DAG of jobs...
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	16	dock
	16	extract_grid_center
	16	get_grid_center
	4	prepare_ligand
	4	prepare_protein
	57

rule prepare_protein:
    input: data/proteins/2am9.pdb
    output: output/proteins_prep/2am9.pdbqt
    jobid: 20
    wildcards: protein=2am9


rule prepare_protein:
    input: data/proteins/4lnx_noalter.pdb
    output: output/proteins_prep/4lnx_noalter.pdbqt
    jobid: 15
    wildcards: protein=4lnx_noalter


rule prepare_protein:
    input: data/proteins/3ert.pdb
    output: output/proteins_prep/3ert.pdbqt
    jobid: 1
    wildcards: protein=3ert


rule prepare_protein:
    input: data/proteins/2pin.pdb
    output: output/proteins_prep/2pin.pdbqt
    jobid: 19
    wildcards: protein=2pin

Error in rule prepare_protein:
Error in rule prepare_protein:
    jobid: 15
    jobid: 20
    output: output/proteins_prep/4lnx_noalter.pdbqt
    output: output/proteins_prep/2am9.pdbqt


Error in rule prepare_protein:
    jobid: 1
    output: output/proteins_prep/3ert.pdbqt

RuleException:
CalledProcessError in line 30 of /data/karim_thesis/AutoDock-vina-snakemake-pipeline/Snakefile.py:
Command ' set -euo pipefail;  
        FlipbookApp/mfb/MGLToolsPckgs/AutoDockTools/Utilities24/prepare_receptor4.py -r data/proteins/2am9.pdb -o output/proteins_prep/2am9.pdbqt -A hydrogens  -e True -v ' returned non-zero exit status 1.
  File "/data/karim_thesis/AutoDock-vina-snakemake-pipeline/Snakefile.py", line 30, in __rule_prepare_protein
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
RuleException:
CalledProcessError in line 30 of /data/karim_thesis/AutoDock-vina-snakemake-pipeline/Snakefile.py:
Command ' set -euo pipefail;  
        FlipbookApp/mfb/MGLToolsPckgs/AutoDockTools/Utilities24/prepare_receptor4.py -r data/proteins/4lnx_noalter.pdb -o output/proteins_prep/4lnx_noalter.pdbqt -A hydrogens  -e True -v ' returned non-zero exit status 1.
  File "/data/karim_thesis/AutoDock-vina-snakemake-pipeline/Snakefile.py", line 30, in __rule_prepare_protein
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Error in rule prepare_protein:
    jobid: 19
    output: output/proteins_prep/2pin.pdbqt
Will exit after finishing currently running jobs.

Will exit after finishing currently running jobs.
RuleException:
CalledProcessError in line 30 of /data/karim_thesis/AutoDock-vina-snakemake-pipeline/Snakefile.py:
Command ' set -euo pipefail;  
        FlipbookApp/mfb/MGLToolsPckgs/AutoDockTools/Utilities24/prepare_receptor4.py -r data/proteins/3ert.pdb -o output/proteins_prep/3ert.pdbqt -A hydrogens  -e True -v ' returned non-zero exit status 1.
  File "/data/karim_thesis/AutoDock-vina-snakemake-pipeline/Snakefile.py", line 30, in __rule_prepare_protein
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
RuleException:
CalledProcessError in line 30 of /data/karim_thesis/AutoDock-vina-snakemake-pipeline/Snakefile.py:
Command ' set -euo pipefail;  
        FlipbookApp/mfb/MGLToolsPckgs/AutoDockTools/Utilities24/prepare_receptor4.py -r data/proteins/2pin.pdb -o output/proteins_prep/2pin.pdbqt -A hydrogens  -e True -v ' returned non-zero exit status 1.
  File "/data/karim_thesis/AutoDock-vina-snakemake-pipeline/Snakefile.py", line 30, in __rule_prepare_protein
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-10T171135.011763.snakemake.log
